config/routes.rb
Sampletimeliner::Application.routes.draw do
  get "artist/show"

  devise_for :users

  resources :users

  resources :artists

  resources :songs do
    resources :samples
  end
  root to: "static_pages#home"


end

app/models/artist.rb
class Artist < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessible :bio, :name

  has_many :songs
  #has_many :samples
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  attr_accessible :artist, :name, :song_id, :youtube_id, :second_offset, :start, :duration
  belongs_to :song
  belongs_to :user

  validates :artist, presence: true
  validates :name, presence: true
  validates :youtube_id, presence: true
  validates :second_offset, presence: true
  validates :start, presence: true
  validates :duration, presence: true
end

app/models/song.rb
class Song < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  attr_accessible :name, :youtube_id
  belongs_to :user
  belongs_to :artist
  has_many :samples

  validates :name, presence: true
  validates :youtube_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  extend FriendlyId
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  friendly_id :name, use: :slugged

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body
  has_many :songs
  has_many :samples

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def show
    @artist = Artist.find params[:id]
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_filter :correct_user, only: [:edit, :update]
  before_filter :authenticate_user!, only: [:new, :create]

  def new
    @time = params[:time]
    @song = Song.find params[:song_id]
    @sample = Sample.new
  end

  def create
    @song = Song.find params[:song_id]
    @sample = Sample.new params[:sample]
    @sample.song = @song
    @sample.user = current_user
    if @sample.save
      render :text => '<script type="text/javascript"> window.close() </script>'
      return
    else
      flash.now[:error] = 'Could not create!'
      @time = params[:sample][:second_offset]
      render 'new'
      return
    end
  end

  def edit
    @song = Song.find params[:song_id]
  end

  def update
    @sample.update_attributes params[:sample]
    if @sample.save
      redirect_to song_path(@sample.song)
      return
    else
      flash[:error] = 'There are errors with this sample'
      render 'edit'
      return
    end
  end

  private
    def correct_user
      @sample = Sample.find params[:id]
      unless @sample.user == current_user
        flash[:error] = 'You do not own this sample.'
        redirect_to song_path(@sample.song)
      end
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.paginate page: params[:page], per_page: 20
  end
  def new
    @song = Song.new
  end

  def create
    @song = Song.new params[:song].except(:artist)
    @song.user = current_user
    @artist = Artist.find_or_create_by_name(params[:song][:artist])
    @song.artist = @artist

    if @song.save
      flash[:success] = 'Song created!'
      redirect_to song_path(@song)
    else
      flash[:error] = 'Error'
      render 'new'
    end
  end

  def show
    @song = Song.find(params[:id])
    @colors = [:red, :orange, :green, :blue]
    @samples = @song.samples.map do |sample|
      {
        sample: sample,
        color: @colors.rotate![0]
      }
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    @songs = @user.songs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Sample Timeliner"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end

  def seconds_to_display(seconds)
    puts "CONVERTING #{seconds}"
    mins = seconds / 60
    if mins > 0
      secs = seconds % 60
    else
      secs = seconds
    end
    secs = "0#{secs}" if secs < 10
    "#{mins}:#{secs}"
  end

  def youtube_thumbnail(youtube_id)
    "http://img.youtube.com/vi/#{youtube_id}/0.jpg"
  end
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/artists/show.html.slim
.row
  .span8
    h1 #{@artist.name}
    h2 Songs
    ul
    - @artist.songs.each do |song|
      li #{link_to song.name, song_path(song)}

  .span4
    p #{@artist.bio}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= stylesheet_link_tag params[:controller] %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag params[:controller] %>
    <%= csrf_meta_tags %>
  </head>
<body>

  <header class ="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Sample Timeliner", root_path, id: "logo" %>
        <nav>
          <ul class="nav pull-right">
            <% if user_signed_in? %>
              <li><%= link_to(current_user.name, user_path(current_user)) %></li>
              <li><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %></li>
            <% else %>
              <li><%= link_to "Sign in", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </div>
  </header>

  <div class="container">
    <% if flash[:success] %>
      <p class="alert alert-success"><%= flash[:success] %></p>
    <% end %>
    <% if flash[:notice] %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if flash[:error] %>
      <p class="alert alert-error"><%= flash[:error] %></p>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>

app/views/samples/_form.html.slim
= form_for [song, sample], html: {class: 'form-horizontal'} do |f|
  .control-group
    = f.label :name, class: 'control-label'
    .controls
      =f.text_field :name

  .control-group
    = f.label :artist, class: 'control-label'
    .controls
      = f.text_field :artist

  .control-group
    = f.label :youtube_id, 'Youtube ID', class: 'control-label'
    .controls
      = f.text_field :youtube_id

  .control-group
    = f.label :start, class: 'control-label'
    .controls
      =f.text_field :start

  .control-group
    = f.label :duration, class: 'control-label'
    .controls
      =f.text_field :duration

  .control-group
    = f.label :second_offset, class: 'control-label'
    .controls
      =f.text_field :second_offset, value: sample.second_offset || @time

  .control-group
    .controls
      = f.submit 'Save', class: 'btn'

app/views/samples/edit.html.slim
- provide(:title, 'Edit Sample')
.row
  .span12
    h1 Edit Sample
    hr
    = render 'form', song: @song, sample: @sample

app/views/samples/new.html.slim
.row
  .span12
    h1 Add Sample for #{@song.name}
    hr
    = form_for [@song, @sample], html: {class: 'form-horizontal'} do |f|
      .control-group
        = f.label :name, class: 'control-label'
        .controls
          =f.text_field :name

      .control-group
        = f.label :artist, class: 'control-label'
        .controls
          = f.text_field :artist

      .control-group
        = f.label :youtube_id, 'Youtube ID', class: 'control-label'
        .controls
          = f.text_field :youtube_id

      .control-group
        = f.label :start, class: 'control-label'
        .controls
          =f.text_field :start

      .control-group
        = f.label :duration, class: 'control-label'
        .controls
          =f.text_field :duration

      .control-group
        = f.label :second_offset, class: 'control-label'
        .controls
          =f.text_field :second_offset, value: @time

      .control-group
        .controls
          = f.submit 'Create', class: 'btn'

app/views/songs/_youtube.js.erb
<script>
var tag = document.createElement('script');
tag.src = "http://www.youtube.com/player_api";
var firstScriptTag = document.getElementsByTagName('script')[0];
firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
var player;
var samples = [];
var timelineUpdate;
var Sample = function(youtube_id, start, duration, offset, color, id) {
  this.color = color;
  this.youtube_id = youtube_id;
  this.start = start;
  this.duration = duration;
  this.offset = offset;
  this.id = id;
  this.startTimeout = null;
  this.thisstopTimeout = null;
  this.splayer = new YT.Player(this.youtube_id, {
    height: '100',
    width: '100',
    videoId: this.youtube_id,
    events: {
      'onReady': onPlayerReady,
    }
  });
  this.getPlayer = function() {
    return splayer;
  }
}
Sample.prototype = {
  // Sets a timeout based on currTime (of main video) for this Sample to start
  setTimeouts: function(currTime) {
    var offset = this.start + .1 - currTime;
    if (offset > 0) {
      (function(_this) {
        _this.splayer.unMute();
        _this.splayer.playVideo();
        _this.splayer.seekTo(_this.offset);
        _this.splayer.pauseVideo();
        _this.startTimeout = setTimeout(function(){
          _this.splayer.playVideo();
          _this.splayer.seekTo(_this.offset);
          $('#contain-' + _this.youtube_id + _this.id).addClass('active');
          player.mute();
        }, offset * 1000);
        _this.stopTimeout = setTimeout(function(){
          _this.splayer.pauseVideo();
          $('#contain-' + _this.youtube_id + _this.id).removeClass('active');
          player.unMute();
        }, (offset + _this.duration) * 1000);
      })(this);

    }
  },
  clearTimeouts: function() {
    clearTimeout(this.startTimeout);
    clearTimeout(this.stopTimeout);
  },
}


function onYouTubePlayerAPIReady() {
  player = new YT.Player('player', {
    width: '940',
    height: '200',
    videoId: "<%= song.youtube_id %>",
    events: {
      'onReady': onPlayerReady,
      'onStateChange': onPlayerStateChange
    }
  });
  <% samples.each do |sample| %>
    samples.push(new Sample('<%= sample[:sample].youtube_id %>', <%= sample[:sample].second_offset %>, <%= sample[:sample].duration %>, <%= sample[:sample].start %>, '<%= sample[:color] %>', <%= sample[:sample].id %>));
  <% end %>
}
function onPlayerReady(evt) {
  evt.target.playVideo();
  evt.target.pauseVideo();
}
function onPlayerStateChange(evt) {
  if (evt.data == YT.PlayerState.PLAYING) {
    console.log("playing");
    for (var i = 0; i < samples.length; i++) {
      samples[i].clearTimeouts();
      samples[i].setTimeouts(player.getCurrentTime());
    }
    timelineUpdate = setInterval(function() {draw()}, 50);
  }
  else if (evt.data == YT.PlayerState.PAUSED) {
    console.log("paused");
    for (var i = 0; i < samples.length; i++) {
      samples[i].clearTimeouts();
      samples[i].splayer.pauseVideo();
    }
    clearInterval(timelineUpdate);
  }
  else if (evt.data == YT.PlayerState.CUED) {
    console.log("cued");
  }
  else if (evt.data == -1) {
    draw();
  }
}

function getPlayerTime() {
  return player.getCurrentTime();
}

function draw() {
  var canvas = document.getElementById('timeline');
  if (canvas.getContext) {
    var ctx = canvas.getContext("2d");
    ctx.clearRect(0, 0, 940, 150);

    var offset = (player.getCurrentTime()/player.getDuration());
    ctx.beginPath();
    ctx.moveTo(offset * 940, 85);
    ctx.lineTo(offset * 940, 65);
    ctx.lineTo(offset * 940 + 2, 65);
    ctx.lineTo(offset * 940 + 2, 85);
    ctx.fillStyle = 'black';
    ctx.fill();
    ctx.beginPath();
    ctx.moveTo(0, 75);
    ctx.lineTo(940, 75);
    ctx.closePath();
    ctx.stroke();

    for (var i = 0; i < samples.length; i++) {
      var soffset = samples[i].start / player.getDuration();
      var doffset = soffset + (samples[i].duration / player.getDuration());
      var ydirection;
      if (i % 2 == 0) ydirection = 1;
      else ydirection = -1;
      ctx.beginPath();
      ctx.moveTo(soffset * 940, 75 + (ydirection * 15));
      ctx.lineTo(doffset * 940, 75 + (ydirection * 15));
      ctx.lineTo(doffset * 940, 75 + (ydirection * 20));
      ctx.lineTo(soffset * 940, 75 + (ydirection * 20));
      ctx.lineTo(soffset * 940, 75 + (ydirection * 15));
      ctx.fillStyle = samples[i].color;
      ctx.fill();
      //ctx.closePath();
      //ctx.stroke();
    }
  }
}
</script>

app/views/songs/index.html.slim
h1.title Songs
table
  - @songs.each do |song|
    tr
      td
        img src=youtube_thumbnail(song.youtube_id) width=50
      td
        = link_to "#{song.name} - #{song.artist}", song_path(song)

= will_paginate @songs

app/views/songs/new.html.slim
.row
  .span12
    h1 New Song

    hr

    = form_for @song, html: {class: 'form-horizontal'} do |f|
      .control-group
        = f.label :name, class: 'control-label'
        .controls
          = f.text_field :name

      .control-group
        = f.label :artist, class: 'control-label'
        .controls
          = f.text_field :artist

      .control-group
        = f.label :youtube_id, 'Youtube ID', class: 'control-label'
        .controls
          = f.text_field :youtube_id

      .control-group
        .controls
          = f.submit 'Create', class: 'btn'

app/views/songs/show.html.slim
- provide(:title, "#{@song.name} - #{@song.artist}")
.row
  .span12
    .title
      h1.inline
        =' @song.name
      h3.inline by #{link_to @song.artist.name, artist_path(@song.artist)}
    div#player
    canvas id="timeline" width="940" height="150"
- @samples.each do |sample|
  .row
    .span3
      .sample id="contain-#{sample[:sample].youtube_id}#{sample[:sample].id}"
        div id="#{sample[:sample].youtube_id}"
    .span3.color-label class=sample[:color]
      p
        | "#{sample[:sample].name}" by #{sample[:sample].artist}
        br
        | Starts at #{seconds_to_display sample[:sample].second_offset}
        br
        | Duration: #{sample[:sample].duration} seconds
        br
        = link_to 'Edit', edit_song_sample_path(@song, sample[:sample])

= render 'youtube.js', song: @song, samples: @samples

= link_to 'Add Sample', new_song_sample_path(@song), class: 'popup'

app/views/static_pages/home.html.slim
.hero-unit.center
  h1 welcome to the sample timeliner
  p take a look at some #{link_to 'timelines', songs_path}?

app/views/users/show.html.slim
- provide(:title, @user.name)

.row
  .span8
    h1.title Songs
    table
      - @songs.each do |song|
        tr
          td
            img src=youtube_thumbnail(song.youtube_id) width=50
          td
            = link_to song.name, song_path(song)

  .span4
    h2
      = @user.name
    p Authored #{@songs.count} songs